[package]
name = "game0"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"
rand = "0.9.2"
obj = "0.10.2"
regex = "1"
tokio = {version="1" features=["full"]}
tokio-tungstenite = "0.28.0"
tungstenite = "0.28.0"
futures = "0.3"
websocket = "0.27.1"

